/*
 * Project Miroir Magique
 * Projet qui contrôle le miroir magique
 * 2018 Étudiants de Collège de Bois-de-Boulogne
 */
package MiroirMagique;

import java.io.IOException;
import java.util.*;
import javax.swing.*;
import com.illposed.osc.*;
import java.awt.FontFormatException;
import java.net.SocketException;
import java.util.logging.*;

public class Accueil extends javax.swing.JFrame {

    //Le numéro du port où il faut écouter
    private OSCPortIn receiver;

    //Deux JFrames qui vont être créée
    private EcranNoir ecranNoir;
    private EcranDebut ecranDebut;
    private Process p = null;

    /**
     * Crée nouveau form Accueil Le Gui avec lequel Morpheus interagit
     */
    public Accueil() throws SocketException {
        initComponents();
        this.setLocationRelativeTo(null);

        //Numero du port sur lequel on veut écouter
        int receiverPort = 8888;
        receiver = new OSCPortIn(receiverPort);

        // Un "Message Handler" qui trait tous les messages (s'appelle OSCListener)
        // Il "écoute" pour un message et après le trait
        OSCListener handlerVoyagerTemps = new OSCListener() {
            public void acceptMessage(java.util.Date time, OSCMessage message) {
                try {
                    lancerFutur();
                } catch (Exception ex) {
                }
            }
        };

        OSCListener handlerQuitter = new OSCListener() {
            public void acceptMessage(java.util.Date time, OSCMessage message) {
                quitter();
            }
        };

        OSCListener handlerResetJeu = new OSCListener() {
            public void acceptMessage(java.util.Date time, OSCMessage message) {
                resetJeu();
            }
        };

        //Ajouter les handlers pour les étiquettes qui correspondent
        receiver.addListener("/VoyageDansTemps", handlerVoyagerTemps);
        receiver.addListener("/QuitterMiroir", handlerQuitter);
        receiver.addListener("/ResetJeu", handlerResetJeu);
    }

    /**
     * Cette méthode est appelée pour quitter
     */
    private void quitter() {
        resetJeu();
        System.exit(0);
    }

    /**
     * Cette méthode est appelée pour lancer le programme (début du jeu)
     */
    private void lancerProgramme() {
        this.hide();
        //Affiche l'écran noir
        ecranNoir = new EcranNoir();
        //Ça commence à écouter
        
        receiver.startListening();
        this.show();
    }

    /**
     * Cette méthode est appelée pour lancer le programme (début du jeu) TODO
     * Commenter + expliquer le code suivant TOD-O Nettoyer les print et les
     * messages (plus de description pour être compréhensible
     */
    private void lancerFutur() throws FontFormatException, IOException {
        this.hide();
        try {
            //Roule le script Python pour la reconnaissance d'images
            p = Runtime.getRuntime().exec("python MiroirMagiqueDetection.py");

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Python script ne marche pas", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        ecranDebut = new EcranDebut();
        this.show();
    }

    /**
     * Cette méthode est appelée pour le reset (essaye de fermer les fenêtres
     * ouverts
     */
    private void resetJeu() {
        try {
            //Enlève l'écran de début s'il en a un
            ecranDebut.dispose();

        } catch (Exception ex) {
        }
        try {
            //Roule le script Python pour la reconnaissance d'images
            Process q = Runtime.getRuntime().exec("killjava.bat");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "killjava script ne marche pas", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        p.destroy();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Launch Program");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("Change Picture");

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton6)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(60, 60, 60)
                .addComponent(jButton5)
                .addGap(35, 35, 35)
                .addComponent(jButton6)
                .addGap(26, 26, 26))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Morpheus Magic Mirror App");
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Launch Program");
        jButton1.setName("launch"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton3)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //Bouton "Launch Program" (fait au début de la journée seulement)
            lancerProgramme();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Bouton "Quitter"
        quitter();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * Affiche le JFrame
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Accueil().setVisible(true);
                } catch (Exception ex) {
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    // End of variables declaration//GEN-END:variables
}
